### ISSUE TITLE
Не проходит тест на логин

### ISSUE THREAD

**Issue by alexey-olfert** [alexey-olfert/homework2-4#1]
1. Прошёл все шаги [отсюда](https://github.com/netology-code/aqa-homeworks/tree/master/bdd) под заголовками "Как сдавать задачи" и "Настройка CI".
1. Создал классы "DashboardPage", "LoginPageV1", "VerificationPage" и заполнил их как в презентации.
1. Создал класс TransferMoneyTest, добавил в него первый тест из презентации.
1. Запустил тест

**Ожидаемый результат**
Тест пройден

**Фактический результат**
Ошибка выполнения теста

**Скриншот**
![Screenshot_20191222_151257](https://user-images.githubusercontent.com/56882078/71321739-0ccfda00-24cf-11ea-9d8a-5bdc4cd1261c.jpg)

**Comment by ArRomanov** [comment]
Вам следует переместить класс `DataHelper` в отдельный пакет, иначе java не может импортировать этот класс, пока он находится в корне директории с тестами. Соответственно, надо будет импортировать в других классах `DataHelper`, IDE вам подскажет.
![image](https://user-images.githubusercontent.com/23121947/71321942-2c1c3680-24d2-11ea-9231-0f04e0ea4feb.png)

**Comment by alexey-olfert** [comment]
Переместил классы в пакеты, теперь мне Idea следующую ошибку показывает:
![Screenshot_20191222_155915](https://user-images.githubusercontent.com/56882078/71322072-20ca0a80-24d4-11ea-9e3e-6f1c19211b42.jpg)

**Comment by ArRomanov** [comment]
Вам надо в классах, где эти методы расположены, сделать импорт пакета. Скорее всего будет просто `import data`.

**Comment by alexey-olfert** [comment]
`import data.DataHelper;` есть, а что ему ещё нужно, я не пойму...

**Comment by ArRomanov** [comment]
Сделайте импорт с помощью alt+enter
![image](https://user-images.githubusercontent.com/23121947/71322442-959f4380-24d8-11ea-8df4-c45c8f096a9e.png)
![image](https://user-images.githubusercontent.com/23121947/71322450-a0f26f00-24d8-11ea-9f50-4f0613b7be24.png)

**Comment by alexey-olfert** [comment]
Импорт сделал, теперь IDE не подсвечивает ошибок. Однако, всё равно тест падает:
![Screenshot_20191223_123355](https://user-images.githubusercontent.com/56882078/71349676-a2777200-2580-11ea-9d16-202fc0e18698.jpg)

**Comment by ArRomanov** [comment]
Здесь уже стоит разбираться с тем, что вы написали в тесте. Судя по логам, у вас проблемы с локаторами

**Comment by alexey-olfert** [comment]
Можете посмотреть код? Он есть в репозитории.

**Comment by ArRomanov** [comment]
`public class DashboardPage {
    private SelenideElement heading = $("data-test-id=dashboard");`

У вас селектор невалидный, забыли взять в квадратные скобки - `$("[data-test-id=dashboard]")`

**Comment by alexey-olfert** [comment]
Исправил, всё заработало, спасибо!
